# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4e8ec9ecc4b304a49c6ec97f204a0f0b10ed563daf8e0951a3ff18a633d64deaa753629e5ea4e196902887285f1fb20702e6d86857fe9827615dfd6e848b29a

test:
  secret_key_base: 2f0ce8b30884b5ce9a84303e6ef8f65a3106ecb79929a0900a1b77577b45d28119024cbe623e879d09b7eeeb390e9522765993497948f5b09ec08780e2f66881

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
